package com.amazonaws.lambda.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Board")
public class Board {
	private String boardId;
	private String annoucement;
	private String courseId;

	public Board() {
		
	}	
	
	public Board(String courseId, String annoucement) {
		this.courseId = courseId;
		this.annoucement = annoucement;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}
	
	@DynamoDBAttribute(attributeName = "courseId")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@DynamoDBAttribute(attributeName = "annoucement")
	public String getAnnoucement() {
		return annoucement;
	}

	public void setAnnoucement(String annoucement) {
		this.annoucement = annoucement;
	}

	@Override
	@DynamoDBIgnore
	public String toString() {
		return "Board [boardId=" + boardId + ", annoucement=" + annoucement + "]";
	}	
}
