package com.amazonaws.lambda.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Registrar")
public class Registrar {
	private String registrationId;
	private String offeringId;
	private String offeringType;
	private String department;
	private double perUnitPrice;

	public Registrar() {
		
	}
	
	public Registrar( String offeringId, String offeringType, String department,
			double perUnitPrice) {
		this.offeringId = offeringId;
		this.offeringType = offeringType;
		this.department = department;
		this.perUnitPrice = perUnitPrice;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "registrationId")
	public String getRegistrationId() {
		return registrationId;
	}

	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}

	@DynamoDBAttribute(attributeName="offeringId")
	public String getOfferingId() {
		return offeringId;
	}

	public void setOfferingId(String offeringId) {
		this.offeringId = offeringId;
	}

	@DynamoDBAttribute(attributeName="offeringType")
	public String getOfferingType() {
		return offeringType;
	}

	public void setOfferingType(String offeringType) {
		this.offeringType = offeringType;
	}

	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}
	
	@DynamoDBAttribute(attributeName="perUnitPrice")
	public double getPerUnitPrice() {
		return perUnitPrice;
	}

	public void setPerUnitPrice(double perUnitPrice) {
		this.perUnitPrice = perUnitPrice;
	}

	@Override
	@DynamoDBIgnore
	public String toString() {
		return "Registrar [registrationId=" + registrationId + ", offeringId=" + offeringId + ", offeringType="
				+ offeringType + ", department=" + department + ", perUnitPrice=" + perUnitPrice + "]";
	}

}
